export enum ErrorCode {
  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_REVOKED = 'TOKEN_REVOKED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',
  USER_DELETED = 'USER_DELETED',

  // Organization
  ORG_NOT_FOUND = 'ORG_NOT_FOUND',
  ORG_SLUG_TAKEN = 'ORG_SLUG_TAKEN',
  LAST_ADMIN = 'LAST_ADMIN',

  // Membership
  MEMBERSHIP_NOT_FOUND = 'MEMBERSHIP_NOT_FOUND',
  MEMBERSHIP_ALREADY_EXISTS = 'MEMBERSHIP_ALREADY_EXISTS',
  INVALID_INVITE = 'INVALID_INVITE',
  NOT_ORG_MEMBER = 'NOT_ORG_MEMBER',
  INSUFFICIENT_ROLE = 'INSUFFICIENT_ROLE',

  // General
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
}
